INHERIT: .mkdocs.base.yml

site_name: Embedded Lab
site_description: Laboratory for embedded systems development and learning.
site_url: https://emlab-docs.github.io/

repo_url: https://github.com/Dakata99/embedded-lab
repo_name: Dakata99/embedded-lab

docs_dir: docs

nav:
    - Home: index.md
    - Hello world "driver": hello-world/index.md
    - LED examples:
        - Overview: led/index.md
        - LED: led/led.md
        - 3 LEDs: led/3leds.md
        - LED client: led/led-client.md
    - Tips: tips.md
    - References: references.md
