[project]
name = "embedded-lab"
version = "0.1.0"
description = "Embedded Lab is a collection of resources and tutorials for embedded systems development."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "adafruit-circuitpython-ahtx0>=1.0.30",
    "flask>=3.1.3",
    "gpiozero",
    "lgpio",
    "loguru>=0.7.3",
    "pyinstaller>=6.21.0",
]

[dependency-groups]
dev = [
    "devtools[docs]",
]

[tool.uv.sources]
devtools = { git = "https://github.com/Dakata99/devtools.git", rev = "main" }
