#!/bin/bash

if [[ $(which uv) == "" ]]; then
    echo "Please install uv and try again."
    echo "Command: curl -LsSf https://astral.sh/uv/install.sh | sh"
    exit 1
fi

PROMPT=emlab
export UV_PROJECT_ENVIRONMENT=.$PROMPT
uv venv $UV_PROJECT_ENVIRONMENT --prompt $PROMPT --clear
source $UV_PROJECT_ENVIRONMENT/bin/activate
uv sync --active --quiet
