#!/bin/bash

if [[ $(which uv) == "" ]]; then
    echo "Please install uv (sudo apt install uv) and try again."
    exit 1
fi

PROMPT=emlab
export UV_PROJECT_ENVIRONMENT=.$PROMPT
uv venv $UV_PROJECT_ENVIRONMENT --prompt emlab --clear
source $UV_PROJECT_ENVIRONMENT/bin/activate
uv sync --active --quiet
